### ISSUE TITLE
Use meteor instead of meteorite

### ISSUE THREAD

**Issue by Alber70g** [Pent/generator-meteor#7]
Is it possible to use the meteorite Athmosphere packages instead of Meteorite?

```
NOTE: As of Meteor 0.9.0, Meteorite is no longer required! 
You can now install Atmosphere packages directly via the meteor tool.
```
https://github.com/oortcloud/meteorite

Also Meteorite has no support for Windows.

**Comment by Pent** [comment]
I've removed Meteorite from the dependencies.
