### ISSUE TITLE
What is missing?

### ISSUE THREAD

**Issue by neilyoung** [Pent/generator-meteor#8]
[[[[[ ~/Documents/Meteor/tutorialexample ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
=> Errors prevented startup:                  
   
   While building the application:
   client/styles/theme.less:1:1: Less compiler error:
   '/packages/bootstrap3-less/bootstrap.import.less' wasn't found
   
=> Your application has errors. Waiting for file change.

**Comment by Pent** [comment]
This was caused by a presumably missing meteorite and bootstrap3-less. I've removed both dependencies because of how Meteor continues to treat LESS files (you can't just import Bootstrap's LESS version without some serious configuration).

**Comment by neilyoung** [comment]
Thanks for fixing it. BTW: This works with a plain meteor project

meteor add less
meteor add nemo64:bootstrap

And now it works also with your boilerplate :)
